icd_category_map = {
'Diseases of the Circulatory System'                                                                      : 'Cardiovascular diseases',
'Endocrine, Nutritional and Metabolic Diseases'                                                           : 'Endocrine diseases',
'Diseases of the Digestive System'                                                                        : 'Gastrointestinal diseases',
'Diseases of the Genitourinary System'                                                                    : 'Genitourinary diseases',
'Certain Infectious and Parasitic Diseases'                                                               : 'Infections',
'Injury, Poisoning and Certain Other Consequences of External Causes'                                     : 'Injuries and external causes',
'Mental, Behavioral and Neurodevelopmental Disorders'                                                     : 'Mental and substance use disorders',
'Diseases of the Musculoskeletal System and Connective Tissue'                                            : 'Musculoskeletal diseases',
'Diseases of the Nervous System'                                                                          : 'Nervous system diseases',
'Factors Influencing Health Status and Contact with Health Services'                                      : 'Exclude',
'Symptoms, Signs and Abnormal Clinical and Laboratory Findings, Not Elsewhere Classified'                 : 'Exclude',
'Unacceptable principal diagnosis (inpatient data) or first-listed diagnosis (outpatient data)'           : 'Exclude',
'Diseases of the Blood and Blood Forming Organs and Certain Disorders Involving the Immune Mechanism'     : 'Exclude',
'Diseases of the Ear and Mastoid Process'                                                                 : 'Exclude',
'Diseases of the Eye and Adnexa'                                                                          : 'Exclude',
'Congenital Malformations, Deformations and Chromosomal Abnormalities'                                    : 'Exclude',
'Diseases of the Skin and Subcutaneous Tissue'                                                            : 'Exclude',
'Certain Conditions Originating in the Perinatal Period'                                                  : 'Exclude',
'Pregnancy, Childbirth and the Puerperium'                                                                : 'Exclude',
'Diseases of the Respiratory System'                                                                      : 'Respiratory diseases'
}

us_state_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Northern Mariana Islands": "MP",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Palau": "PW",
    "Pennsylvania": "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virgin Islands": "VI",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

state_fips = {
    "WA": "53",
    "DE": "10",
    "DC": "11",
    "WI": "55",
    "WV": "54",
    "HI": "15",
    "FL": "12",
    "WY": "56",
    "PR": "72",
    "NJ": "34",
    "NM": "35",
    "TX": "48",
    "LA": "22",
    "NC": "37",
    "ND": "38",
    "NE": "31",
    "TN": "47",
    "NY": "36",
    "PA": "42",
    "AK": "02",
    "NV": "32",
    "NH": "33",
    "VA": "51",
    "CO": "08",
    "CA": "06",
    "AL": "01",
    "AR": "05",
    "VT": "50",
    "IL": "17",
    "GA": "13",
    "IN": "18",
    "IA": "19",
    "MA": "25",
    "AZ": "04",
    "ID": "16",
    "CT": "09",
    "ME": "23",
    "MD": "24",
    "OK": "40",
    "OH": "39",
    "UT": "49",
    "MO": "29",
    "MN": "27",
    "MI": "26",
    "RI": "44",
    "KS": "20",
    "MT": "30",
    "MS": "28",
    "SC": "45",
    "KY": "21",
    "OR": "41",
    "SD": "46",
}

state_list = [
    "AK",
    "AL",
    "AR",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "GA",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY",
]

disease_rename_map = {
    'd_neoplasms':'Neoplasms',
    'd_cardiovascular_diseases':'Cardiovascular diseases',
    'd_nervous_system_diseases':'Nervous system diseases',
    'd_infections':'Infections',
    'd_injuries_and_external_causes':'Injuries and external causes',
    'd_respiratory_diseases':'Respiratory diseases',
    'd_genitourinary_diseases':'Genitourinary diseases',
    'd_gastrointestinal_diseases':'Gastrointestinal diseases',
    'd_musculoskeletal_diseases':'Musculoskeletal diseases',
    'd_mental_and_substance_use_disorders':'Mental health disorders',
    'd_endocrine_diseases':'Endocrine diseases'
}
